# Generated by Django 4.2.23 on 2025-08-28 20:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Name', max_length=255)),
                ('prof_note', models.TextField(blank=True, null=True)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('meeting_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prof_link', models.UUIDField(blank=True, null=True)),
                ('prof_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prof_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('prof_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('prof_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('prof_role', models.CharField(blank=True, max_length=255, null=True)),
                ('prof_more_about', models.TextField(blank=True, null=True)),
                ('prof_selected_time', models.DateTimeField(blank=True, null=True)),
                ('prof_note', models.TextField(blank=True, null=True)),
                ('prof_assigned', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TimeOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_options', to='meetings.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('seeking_service', models.CharField(blank=True, max_length=20, null=True)),
                ('resume_upload', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('hear_about', models.CharField(blank=True, max_length=100, null=True)),
                ('optional_info', models.TextField(blank=True, null=True)),
                ('send_to_email', models.BooleanField(default=False)),
                ('prof_assigned', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='meetings.meeting')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='meetings.professional')),
            ],
        ),
    ]
