# Generated by Django 4.2.23 on 2025-07-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_meeting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityresponse',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=254),
        ),
    ]
