# Generated by Django 4.2.23 on 2025-08-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_availabilityresponse_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityresponse',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('professional', 'Professional')], default='student', max_length=12),
            preserve_default=False,
        ),
    ]
