# Generated by Django 4.2.23 on 2025-08-14 16:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_availabilityresponse_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfessionalPair',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='meetings.meeting')),
                ('professional', models.ForeignKey(limit_choices_to={'role': 'professional'}, on_delete=django.db.models.deletion.CASCADE, related_name='professional_pairs', to='meetings.availabilityresponse')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_pairs', to='meetings.availabilityresponse')),
                ('time_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paired_sessions', to='meetings.timeoption')),
            ],
            options={
                'unique_together': {('student', 'professional', 'time_option')},
            },
        ),
    ]
