# Generated by Django 4.2.23 on 2025-08-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_availabilityresponse_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityresponse',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='availabilityresponse',
            name='hear_about_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='availabilityresponse',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='availabilityresponse',
            name='optional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availabilityresponse',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='availabilityresponse',
            name='resume_upload',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='availabilityresponse',
            name='seeking_service',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='availabilityresponse',
            name='send_to_email',
            field=models.BooleanField(default=False),
        ),
    ]
