# Generated by Django 4.2.23 on 2025-08-19 19:27

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_availabilityresponse_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('seeking_service', models.CharField(blank=True, max_length=20, null=True)),
                ('resume_upload', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('hear_about_service', models.CharField(blank=True, max_length=100, null=True)),
                ('optional_information', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('professional_assigned', models.BooleanField(default=False)),
                ('professional_link', models.UUIDField(blank=True, null=True)),
                ('professional_name', models.CharField(blank=True, max_length=255, null=True)),
                ('professional_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('professional_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('professional_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('professional_role', models.CharField(blank=True, max_length=255, null=True)),
                ('professional_more_about', models.TextField(blank=True, null=True)),
                ('professional_selected_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
