# Generated by Django 4.2.23 on 2025-08-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_studentprofessionalpair'),
        ('meetings', '0008_studentsubmission'),
    ]

    operations = [
    ]
