# Generated by Django 4.2.23 on 2025-08-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_merge_20250821_1918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfessionalPair',
        ),
    ]
