# Generated by Django 4.2.23 on 2025-08-23 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_delete_studentprofessionalpair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prof_link', models.UUIDField(blank=True, null=True)),
                ('prof_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prof_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('prof_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('prof_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('prof_role', models.CharField(blank=True, max_length=255, null=True)),
                ('prof_more_about', models.TextField(blank=True, null=True)),
                ('prof_selected_time', models.DateTimeField(blank=True, null=True)),
                ('prof_note', models.TextField(blank=True, null=True)),
                ('prof_assigned', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('seeking_service', models.CharField(blank=True, max_length=20, null=True)),
                ('resume_upload', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('hear_about', models.CharField(blank=True, max_length=100, null=True)),
                ('optional_info', models.TextField(blank=True, null=True)),
                ('send_to_email', models.BooleanField(default=False)),
                ('prof_assigned', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='availabilityentry',
            name='availability_response',
        ),
        migrations.RemoveField(
            model_name='availabilityentry',
            name='time_option',
        ),
        migrations.RemoveField(
            model_name='availabilityresponse',
            name='meeting',
        ),
        migrations.DeleteModel(
            name='StudentSubmission',
        ),
        migrations.AddField(
            model_name='meeting',
            name='prof_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AvailabilityEntry',
        ),
        migrations.DeleteModel(
            name='AvailabilityResponse',
        ),
        migrations.AddField(
            model_name='student',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='professional',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionals', to='meetings.meeting'),
        ),
    ]
