# Generated by Django 4.2.23 on 2025-08-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_professional_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
